DROP TABLE livres;
CREATE TABLE livres (
Categorie VARCHAR(50) NOT NULL,
Titre VARCHAR(100) NOT NULL ,
Auteur VARCHAR(50) NOT NULL ,
DatePar DATE NOT NULL ,
Editeur VARCHAR(50) NOT NULL ,
Format VARCHAR(20) NOT NULL ,
PrixN DOUBLE DEFAULT '0' NOT NULL ,
ISBN VARCHAR(50) NOT NULL,
PRIMARY KEY ( ISBN )
);

DROP TABLE agents;
CREATE TABLE agents (
nomPDM VARCHAR( 50 ) NOT NULL ,
nomAgent VARCHAR( 50 ) NOT NULL ,
argent DOUBLE NOT NULL ,
categorie VARCHAR( 50 ) NOT NULL ,
PRIMARY KEY ( nomAgent )
);

DROP TABLE pdms;
CREATE TABLE pdms (
nom varchar(50) NOT NULL default '',
adresse varchar(50) NOT NULL default '',
PRIMARY KEY ( nom )
);


DROP TABLE items;
CREATE TABLE items (
ID INT(6) NOT NULL auto_increment,
ISBN VARCHAR(50) NOT NULL,
Etat FLOAT DEFAULT '1' NOT NULL,
Proprio VARCHAR(50) NOT NULL ,
PrixAchat FLOAT DEFAULT '0' NOT NULL,
PRIMARY KEY ( ID )
);
