package bourse.agent;

/*
 * Demarrage.java
 *
 * Created on 3 février 2004, 17:40
 */

/**
 *
 * @author  eric
 */
public class Demarrage extends javax.swing.JFrame {
    
    /** Creates new form Demarrage */
    public Demarrage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelAgent = new javax.swing.JPanel();
        jLabelNomAgent = new javax.swing.JLabel();
        jComboBoxNomAgent = new javax.swing.JComboBox();
        jLabelControleAgent = new javax.swing.JLabel();
        jComboBoxControleAgent = new javax.swing.JComboBox();
        jCheckBoxVerbose = new javax.swing.JCheckBox();
        jPanelPdm = new javax.swing.JPanel();
        jLabelPortPdm = new javax.swing.JLabel();
        jTextFieldPortPdm = new javax.swing.JTextField();
        jLabelAdresseIpPdm = new javax.swing.JLabel();
        jTextFieldAdresseIpPdm = new javax.swing.JTextField();
        jPanelValidation = new javax.swing.JPanel();
        jButtonValider = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.FlowLayout());

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanelPrincipal.setLayout(new java.awt.BorderLayout());

        jPanelAgent.setLayout(new java.awt.GridLayout(3, 2));

        jLabelNomAgent.setText("Nom");
        jPanelAgent.add(jLabelNomAgent);

        jComboBoxNomAgent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arnaud", "Barney", "Corie", "Doris", "Eric", "Felicien", "Gatien", "Hortentia", "Icare", "Jerome", "Kholia", "Luther", "Mohamed", "Natacha", "Omer", "Petra", "Quincy", "Rebecca", "Sebastien", "Thadeus", "Ursule", "Vincenzo", "Whitney", "Xena", "Yseult", "Zdzislawa" }));
        jPanelAgent.add(jComboBoxNomAgent);

        jLabelControleAgent.setText("Contr\u00f4le");
        jPanelAgent.add(jLabelControleAgent);

        jComboBoxControleAgent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Intelligence Artificielle", "Humain", "Aléatoire" }));
        jPanelAgent.add(jComboBoxControleAgent);

        jCheckBoxVerbose.setText("mode verbeux");
        jPanelAgent.add(jCheckBoxVerbose);

        jPanelPrincipal.add(jPanelAgent, java.awt.BorderLayout.NORTH);

        jPanelPdm.setLayout(new java.awt.GridLayout(2, 2));

        jPanelPdm.setBorder(new javax.swing.border.TitledBorder("Pdm"));
        jLabelPortPdm.setText("Port");
        jPanelPdm.add(jLabelPortPdm);

        jPanelPdm.add(jTextFieldPortPdm);

        jLabelAdresseIpPdm.setText("Adresse Ip");
        jPanelPdm.add(jLabelAdresseIpPdm);

        jTextFieldAdresseIpPdm.setColumns(15);
        jPanelPdm.add(jTextFieldAdresseIpPdm);

        jPanelPrincipal.add(jPanelPdm, java.awt.BorderLayout.CENTER);

        jButtonValider.setText("Lancer");
        jButtonValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonValiderMouseClicked(evt);
            }
        });

        jPanelValidation.add(jButtonValider);

        jPanelPrincipal.add(jPanelValidation, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelPrincipal);

        pack();
    }//GEN-END:initComponents

    private void jButtonValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonValiderMouseClicked
        // Add your handling code here:
    }//GEN-LAST:event_jButtonValiderMouseClicked
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Demarrage().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAdresseIpPdm;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JComboBox jComboBoxControleAgent;
    private javax.swing.JPanel jPanelAgent;
    private javax.swing.JPanel jPanelPdm;
    private javax.swing.JComboBox jComboBoxNomAgent;
    private javax.swing.JTextField jTextFieldPortPdm;
    private javax.swing.JCheckBox jCheckBoxVerbose;
    private javax.swing.JLabel jLabelPortPdm;
    private javax.swing.JTextField jTextFieldAdresseIpPdm;
    private javax.swing.JPanel jPanelValidation;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JLabel jLabelControleAgent;
    private javax.swing.JLabel jLabelNomAgent;
    // End of variables declaration//GEN-END:variables
    
}
