/*
 * Prout.java
 *
 * Created on 31 janvier 2004, 16:07
 */

package bourse.reseau;

import bourse.protocole.Protocole;
import java.awt.Color;

/**
 *
 * @author  banou
 */
public class ConfigurationBd extends javax.swing.JFrame {
    
    /** Creates new form ConfigurationBd */
    public ConfigurationBd() {
        initComponents();
        initialiserParametres();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanelConteneur = new javax.swing.JPanel();
        jPanelConteneurVariables = new javax.swing.JPanel();
        jPanelVariables = new javax.swing.JPanel();
        jLabelServeur = new javax.swing.JLabel();
        jTextFieldServeur = new javax.swing.JTextField();
        jLabelPort = new javax.swing.JLabel();
        jTextFieldPort = new javax.swing.JTextField();
        jLabelUtilisateur = new javax.swing.JLabel();
        jTextFieldUtilisateur = new javax.swing.JTextField();
        jLabelMotDePasse = new javax.swing.JLabel();
        jPasswordFieldMotDePasse = new javax.swing.JPasswordField();
        jLabelBaseDeDonnees = new javax.swing.JLabel();
        jTextFieldBaseDeDonnees = new javax.swing.JTextField();
        jPanelBouttons = new javax.swing.JPanel();
        jButtonEnregistrer = new javax.swing.JButton();
        jButtonRecharger = new javax.swing.JButton();
        jButtonTester = new javax.swing.JButton();
        jPanelStatut = new javax.swing.JPanel();
        jLabelStatut = new javax.swing.JLabel();
        jPanelSupprimerPdm = new javax.swing.JPanel();
        jLabelSupprimerPdm1 = new javax.swing.JLabel();
        jTextFieldNomPdm = new javax.swing.JTextField();
        jLabelSupprimerPdm2 = new javax.swing.JLabel();
        jButtonSupprimerPdm = new javax.swing.JButton();

        setTitle("Configuration MySQL");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanelConteneur.setLayout(new java.awt.BorderLayout());

        jPanelConteneur.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10)), new javax.swing.border.EtchedBorder()));
        jPanelVariables.setLayout(new java.awt.GridLayout(5, 2, 10, 2));

        jLabelServeur.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelServeur.setText("serveur");
        jLabelServeur.setToolTipText("adresse du serveur MySQL");
        jPanelVariables.add(jLabelServeur);

        jPanelVariables.add(jTextFieldServeur);

        jLabelPort.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPort.setText("port");
        jPanelVariables.add(jLabelPort);

        jPanelVariables.add(jTextFieldPort);

        jLabelUtilisateur.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelUtilisateur.setText("utilisateur");
        jPanelVariables.add(jLabelUtilisateur);

        jPanelVariables.add(jTextFieldUtilisateur);

        jLabelMotDePasse.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelMotDePasse.setText("mot de passe");
        jPanelVariables.add(jLabelMotDePasse);

        jPanelVariables.add(jPasswordFieldMotDePasse);

        jLabelBaseDeDonnees.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelBaseDeDonnees.setText("base de donn\u00e9es");
        jPanelVariables.add(jLabelBaseDeDonnees);

        jPanelVariables.add(jTextFieldBaseDeDonnees);

        jPanelConteneurVariables.add(jPanelVariables);

        jPanelConteneur.add(jPanelConteneurVariables, java.awt.BorderLayout.CENTER);

        jButtonEnregistrer.setText("Enregistrer");
        jButtonEnregistrer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEnregistrerMouseClicked(evt);
            }
        });

        jPanelBouttons.add(jButtonEnregistrer);

        jButtonRecharger.setText("Recharger");
        jButtonRecharger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRechargerMouseClicked(evt);
            }
        });

        jPanelBouttons.add(jButtonRecharger);

        jButtonTester.setText("Tester");
        jButtonTester.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTesterMouseClicked(evt);
            }
        });

        jPanelBouttons.add(jButtonTester);

        jPanelConteneur.add(jPanelBouttons, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanelConteneur, java.awt.BorderLayout.CENTER);

        jPanelStatut.setLayout(new java.awt.BorderLayout());

        jLabelStatut.setText(" ");
        jPanelStatut.add(jLabelStatut, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelStatut, java.awt.BorderLayout.SOUTH);

        jPanelSupprimerPdm.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 0, 10)), new javax.swing.border.EtchedBorder()));
        jLabelSupprimerPdm1.setText("Supprimer la place de march\u00e9 nomm\u00e9e");
        jPanelSupprimerPdm.add(jLabelSupprimerPdm1);

        jTextFieldNomPdm.setColumns(10);
        jTextFieldNomPdm.setText("Groupe-E");
        jPanelSupprimerPdm.add(jTextFieldNomPdm);

        jLabelSupprimerPdm2.setText("de la base de donn\u00e9es");
        jPanelSupprimerPdm.add(jLabelSupprimerPdm2);

        jButtonSupprimerPdm.setText("OK");
        jButtonSupprimerPdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSupprimerPdmMouseClicked(evt);
            }
        });

        jPanelSupprimerPdm.add(jButtonSupprimerPdm);

        getContentPane().add(jPanelSupprimerPdm, java.awt.BorderLayout.NORTH);

        pack();
    }//GEN-END:initComponents

    private void jButtonSupprimerPdmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSupprimerPdmMouseClicked
        String nomPlaceDeMarche = jTextFieldNomPdm.getText();
        try {
            bourse.reseau.Bd bd = new bourse.reseau.Bd(false);
            if ((
                bd.requete("DELETE FROM agents WHERE nomPDM = '" + nomPlaceDeMarche + "'") +
                bd.requete("DELETE FROM pdms WHERE nom = '" + nomPlaceDeMarche + "'") +
                bd.requete("DELETE FROM items WHERE Proprio = '" + nomPlaceDeMarche + "'")
            ) == 0) {
                // La requete a échouée
                jLabelStatut.setForeground(Color.red);
                jLabelStatut.setText(jTextFieldNomPdm.getText() + " n'existait pas dans la base");
            } else {
                jLabelStatut.setForeground(Color.black);
                jLabelStatut.setText(jTextFieldNomPdm.getText() + " a été supprimée");
            }
            bd.deconnexion();
        } catch (Exception e) {
            jLabelStatut.setForeground(Color.red);
            jLabelStatut.setText(e.toString());
        }
    }//GEN-LAST:event_jButtonSupprimerPdmMouseClicked

    private void jButtonTesterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTesterMouseClicked
        try {
            new bourse.reseau.Bd(false);
            jLabelStatut.setForeground(Color.black);
            jLabelStatut.setText("Les paramètres sont corrects");
        } catch (Exception e) {
            jLabelStatut.setForeground(Color.red);
            jLabelStatut.setText(e.toString());
        }
    }//GEN-LAST:event_jButtonTesterMouseClicked

    private void jButtonRechargerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRechargerMouseClicked
        initialiserParametres();
        jLabelStatut.setForeground(Color.black);
        jLabelStatut.setText("Paramètres rechargés");
    }//GEN-LAST:event_jButtonRechargerMouseClicked

    public void initialiserParametres() {
        jTextFieldServeur.setText(Protocole.parametresBd.getHote());
        jTextFieldPort.setText(String.valueOf(Protocole.parametresBd.getPort()));
        jTextFieldUtilisateur.setText(Protocole.parametresBd.getUtilisateur());
        jPasswordFieldMotDePasse.setText(Protocole.parametresBd.getMotDePasse());
        jTextFieldBaseDeDonnees.setText(Protocole.parametresBd.getBaseDeDonnees());
    }
    
    private void jButtonEnregistrerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEnregistrerMouseClicked
        try {
            Protocole.parametresBd.setParametres(
                jTextFieldServeur.getText(),
                Integer.parseInt(jTextFieldPort.getText()),
                jTextFieldUtilisateur.getText(),
                String.valueOf(jPasswordFieldMotDePasse.getPassword()),
                jTextFieldBaseDeDonnees.getText()
            );
            Protocole.parametresBd.sauvegarde();
            jLabelStatut.setForeground(Color.black);
            jLabelStatut.setText("Paramètres sauvegardés");
        } catch (NumberFormatException e) {
            // L'utilisateur n'a pas rentré un entier pour le port.
            jLabelStatut.setForeground(Color.red);
            jLabelStatut.setText("Le port doit-être un entier.");
        }

    }//GEN-LAST:event_jButtonEnregistrerMouseClicked
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new ConfigurationBd().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelSupprimerPdm1;
    private javax.swing.JPanel jPanelConteneurVariables;
    private javax.swing.JPanel jPanelBouttons;
    private javax.swing.JTextField jTextFieldNomPdm;
    private javax.swing.JLabel jLabelBaseDeDonnees;
    private javax.swing.JPanel jPanelStatut;
    private javax.swing.JLabel jLabelMotDePasse;
    private javax.swing.JTextField jTextFieldPort;
    private javax.swing.JPasswordField jPasswordFieldMotDePasse;
    private javax.swing.JLabel jLabelUtilisateur;
    private javax.swing.JLabel jLabelStatut;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JTextField jTextFieldServeur;
    private javax.swing.JButton jButtonSupprimerPdm;
    private javax.swing.JButton jButtonTester;
    private javax.swing.JButton jButtonEnregistrer;
    private javax.swing.JLabel jLabelServeur;
    private javax.swing.JPanel jPanelSupprimerPdm;
    private javax.swing.JPanel jPanelConteneur;
    private javax.swing.JLabel jLabelSupprimerPdm2;
    private javax.swing.JButton jButtonRecharger;
    private javax.swing.JTextField jTextFieldBaseDeDonnees;
    private javax.swing.JPanel jPanelVariables;
    private javax.swing.JTextField jTextFieldUtilisateur;
    // End of variables declaration//GEN-END:variables
    
}
