package bourse.protocole;

public enum TypeMessage {
                
    INCONNU,
    WELCOME,
    RESULTWELCOME,
    BYE,
    ERREUR,
    REQUETEPROGRAMME,
    RESULTPROPOSEVENTE,
    PROPOSEVENTE,
    PROPOSITIONENCHEREA,
    RESULTAT,
    RESULTBYE,
    WELCOMEAGENT,
    PROPOSITIONENCHEREP,
    PROPOSITIONENCHERE,
    PROGRAMME,
    REQUETEAGENTS,
    RESULTAGENTS,
    ADMIN;

}